# Generated by Django 5.1.14 on 2026-04-06 17:50

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Default Aarambha Store Shipping", max_length=80
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inside_valley_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "outside_valley_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("free_inside_valley", models.BooleanField(default=False)),
                ("free_delivery_all_nepal", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="ShippingSettings",
        ),
        migrations.AddIndex(
            model_name="shippingconfig",
            index=models.Index(
                fields=["is_active"], name="shipping_sh_is_acti_dcb511_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="shipping_single_active_config",
            ),
        ),
    ]
