# Generated by Django 5.1.14 on 2026-04-06 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_order_rejection_reason_required_and_more"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="promocode",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["code"], name="promotions__code_2587f5_idx"),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["is_active"], name="promotions__is_acti_9af606_idx"
            ),
        ),
        migrations.AddField(
            model_name="promousage",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_usage",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="promousage",
            name="promo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="promotions.promocode",
            ),
        ),
        migrations.AddField(
            model_name="promousage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="promousage",
            constraint=models.UniqueConstraint(
                fields=("promo", "user", "order"), name="unique_promo_usage_user_order"
            ),
        ),
    ]
